Proyecto MVC financiera/Controllers/CreditoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Proyecto_MVC_financiera.Models;

namespace Proyecto_MVC_financiera.Controllers
{
    public class CreditoController : Controller
    {
         
        /*SECCION SOLICITUD CREDITO*/
        public ActionResult Credito()
        {
            if (TempData.ContainsKey("legajo"))
            {
                var leg = (int)TempData["legajo"];
                TempData["legajo"] = leg;
            }
            ViewBag.Planes = new SelectList(Repositorio.Instance.Planes, "NumPlan", "Descripcion");
            return View();
        }
        [HttpGet]
        public ActionResult EstadoCliente(int dni)
        {
            try
            {
                int leg = 0;
                if (TempData.ContainsKey("legajo"))
                {
                    leg = (int)TempData["legajo"];
                    TempData["legajo"] = leg;
                }
                var c = Repositorio.Instance.Clientes.Where(x => x.Dni == dni).FirstOrDefault();
                var empleado = Repositorio.Instance.Empleados.Where(e => e.Legajo == leg).FirstOrDefault();

                //var estado = empleado.Terminal.OtenerEstadoCliente(Repositorio.Instance.Financiera.CodigoFinanciera, c.Dni);

                if (false /*estado.CantidadCreditosActivos > 3 || estado.TieneDeudas == true*/)
                {
                    return Json(new
                    {
                        mjs = "Este Cliente no puede obtener un nuevo credito!!",
                        alert = "alert alert-danger",
                        validacion = false,
                    }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new
                    {
                        mjs = "Puede otorgar un nuevo credito al Cliente!!",
                        alert = "alert alert-success",
                        validacion = true,
                    }, JsonRequestBehavior.AllowGet);
                }
                //return RedirectToAction("Credito");
            }
            catch (Exception ex)
            {
                throw ex;
                //return View();
            }
        }

        [HttpPost]
        public ActionResult CrearCredito(double monto, int plan, int dni)
        {
            try
            {
                int leg = 0;
                if (TempData.ContainsKey("legajo"))
                {
                    leg = (int)TempData["legajo"];
                    TempData["legajo"] = leg;
                }
                string Mjs;
                string Alert;
                bool Validacion = false;
                bool Abonar = false;
                int numCredi = 0;
                if (monto <= Repositorio.Instance.Financiera.MontoMaximoSolicitado)
                {
                    var credito = new Credito();
                    credito.CrearCredito(monto, plan, dni, leg);

                    var empleado = Repositorio.Instance.Empleados.Where(e => e.Legajo == leg).FirstOrDefault();
                    //var informeCreditoOtorgado = empleado.Terminal.InformarCreditoOtorgado(Repositorio.Instance.Financiera.CodigoFinanciera, dni, credito.Numero.ToString(), credito.MontoTotal);

                    //credito.Estado = informeCreditoOtorgado.OperacionValida == false ? Estados.pendiente : Estados.activo;

                    if (true/*credito.Estado.Equals(Estados.activo)*/)
                    {
                        Mjs = "El Credito esta " + "Activo";//credito.Estado.ToString();
                        Alert = "alert alert-success";
                        Validacion = true;
                    }
                    else
                    {
                        Mjs = "El Credito esta " + "inactivo";//credito.Estado.ToString();
                        Alert = "alert alert-warning";
                        Validacion = false;
                    }
                    if (credito.Plan.GetType() == typeof(CuotaAdelantada))
                    {
                        Abonar = true;
                    }
                    Repositorio.Instance.Creditos.Add(credito);
                    numCredi = credito.Numero;
                    return Json(new
                    {
                        mjs = Mjs,
                        alert = Alert,
                        abonar = Abonar,
                        validacion = Validacion,
                        botonImprimir = numCredi,
                    }, JsonRequestBehavior.AllowGet);
                    //return RedirectToAction("Credito");
                }
                else
                {
                    return Json(new
                    {
                        mjs = "El monto no puede ser super a los $100.000!!",
                        alert = "alert alert-danger",
                        abonar = Abonar,
                        validacion = false,
                        botonImprimir = numCredi,
                    }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                throw ex;
                //return View();
            }
        }

        [HttpGet]
        public ActionResult ImprimirComprobante(int numCredito)
        {
            var credito = Repositorio.Instance.Creditos.Where(c => c.Numero == numCredito).FirstOrDefault();

            return PartialView(credito);
        }
    }
}

Proyecto MVC financiera/Controllers/CuotaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Proyecto_MVC_financiera.Models;

namespace Proyecto_MVC_financiera.Controllers
{
    public class CuotaController : Controller
    {
        public ActionResult Cuota()
        {
            if (TempData.ContainsKey("legajo"))
            {
                var leg = (int)TempData["legajo"];
                TempData["legajo"] = leg;
            }
            return View();
        }

        public ActionResult GetDatosCreditos(int dni,int formaDePago)
        {
            if (TempData.ContainsKey("legajo"))
            {
                var leg = (int)TempData["legajo"];
                TempData["legajo"] = leg;
            }
            var lstCred = Repositorio.Instance.Creditos.Where(c => c.ClientePertenece == dni).ToList();
            int cont = 0;

            foreach (var credito in lstCred)
            {
                foreach (var cuota in credito.Cuotas)
                {
                    if (cuota.Saldo != 0 && cuota.Vencimiento < DateTime.Now)
                    {
                        cont += 1;
                        TimeSpan ts = DateTime.Now - cuota.Vencimiento;
                        int diasVencidos = ts.Days;
                        cuota.Saldo = cuota.Monto + (cuota.Monto * (credito.Interes * diasVencidos)) / 100;
                        if (cont >= 2)
                        {
                            credito.Estado = Estados.moroso;
                        }
                    }
                }
                cont = 0;
            }
            switch (formaDePago)
            {
                case 0:
                    return PartialView("GetDatosCreditos",lstCred);

                case 1:
                    return PartialView("GetDatosCreditos",lstCred);
                
                case 2:
                    return PartialView("GetPagoCreditoAll",lstCred);
                default:
                    break;
            }
            return PartialView(lstCred);
        }
        [HttpPost]
        public ActionResult Pago(List<JsonPagos> JsonPagos, double monto,int  dni)
        {
            int legajo =0;
            if (TempData.ContainsKey("legajo"))
            {
                legajo = (int)TempData["legajo"];
                TempData["legajo"] = legajo;
            }
            try
            {
                var empleado = Repositorio.Instance.Empleados.Where(x => x.Legajo== legajo).FirstOrDefault();
                var cliente = Repositorio.Instance.Clientes.Where(c => c.Dni == dni).FirstOrDefault();

                var p = empleado.CrearPago(cliente, monto);

                foreach (var pagar in JsonPagos)
                {
                    var Num_Credito = pagar.NumeroCredito;
                    var Num_Cuota = pagar.NumeroCuota;
                    var cuota = Repositorio.Instance.Creditos.Where(c => c.Numero == Num_Credito).FirstOrDefault().Cuotas.Where(cu => cu.NumCuota == Num_Cuota).FirstOrDefault();
                    p.CrearLinea(cuota, Num_Credito);
                }

                p.CalcularTotal();

                p.Pagar();
                p.VerificarEstadosCreditos(cliente);

                Repositorio.Instance.Pagos.Add(p);
                return PartialView("ReciboPago");
            }
            catch (Exception)
            {

                throw;
            }
        }
    }
}

Proyecto MVC financiera/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - LA FINANCIERA</title>
    @Styles.Render("~/Content/css")
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="~/Content/DataTables/media/css/jquery.dataTables.css">


    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cerrar Sesión", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Gestion Cliente", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Solicitar Credito", "Credito", "Credito")</li>
                    <li><a href="~/Cuota/Cuota" title="Haz Click en el link para abonar la 1° Cuota" data-toggle="popover" data-placement="bottom" data-content="">Abonar Cuota</a></li>
                    @*<li>@Html.ActionLink("Abonar Cuota", "Cuota", "Home")</li>*@
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script>
        $(function () {
            $(".navbar-brand").css("display", "none");
            $(".navbar-nav").css("display", "none");
        });

    </script>
    <script type="text/javascript" charset="utf8" src="~/Scripts/DataTables/media/js/jquery.dataTables.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>